import type { Policy } from "../../types";

export const hipaaPolicy: Policy = {
  id: "hipaa",
  name: "HIPAA Compliance",
  description:
    "Health Insurance Portability and Accountability Act — 18 PHI identifiers",
  enabled: false,
  rules: [
    {
      name: "Redact Patient Names",
      description: "PHI identifier #1 — Names",
      action: "redact",
      direction: "both",
      entityTypes: ["PERSON"],
      patternNames: [],
      severity: "critical",
      enabled: true,
    },
    {
      name: "Redact Medical Record Numbers",
      description: "PHI identifier #8 — Medical record numbers",
      action: "redact",
      direction: "both",
      entityTypes: ["MEDICAL_LICENSE"],
      patternNames: [],
      severity: "critical",
      enabled: true,
    },
    {
      name: "Redact SSN",
      description: "PHI identifier #7 — Social Security numbers",
      action: "redact",
      direction: "both",
      entityTypes: [],
      patternNames: ["SSN"],
      severity: "critical",
      enabled: true,
    },
    {
      name: "Redact Dates",
      description: "PHI identifier #3 — Dates related to individuals",
      action: "redact",
      direction: "both",
      entityTypes: ["DATE_TIME"],
      patternNames: [],
      severity: "medium",
      enabled: true,
    },
    {
      name: "Redact Contact Info",
      description: "PHI identifiers #4,5,6 — Phone, fax, email",
      action: "redact",
      direction: "both",
      entityTypes: ["PHONE_NUMBER", "EMAIL_ADDRESS"],
      patternNames: ["PHONE", "EMAIL"],
      severity: "high",
      enabled: true,
    },
    {
      name: "Redact Location",
      description: "PHI identifier #2 — Geographic data",
      action: "redact",
      direction: "both",
      entityTypes: ["LOCATION"],
      patternNames: [],
      severity: "high",
      enabled: true,
    },
  ],
};
